package qlhocsinh.GUI;

import java.util.ArrayList;
import java.util.*;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import qlhocsinh.BLO.QuanLyHocSinhBLO;
import qlhocsinh.DAO.*;
import qlhocsinh.DTO.*;
import qlhocsinh.GUI.DangnhapGUI;

/**
 *
 * @author DuoNg_Xt_685
 */
public class QuanlyhocsinhGUI extends javax.swing.JFrame {

    private Object[] colName = new Object[]{"Tên Học Sinh", "Mã Học Sinh", "Giới tính", "Ngày Sinh", "Quê Quán", "Số Điện Thoại", "Lớp"};
    HocSinhDAO hocsinh = new HocSinhDAO();

    /**
     * Creates new form Manage
     */
    public QuanlyhocsinhGUI() {
        initComponents();
        List<HocSinhDTO> list = hocsinh.getAll();
        uploaddata(list);
        combobox();
    }

    public void combobox() {
//        String[] s = {"A","B","C","D","E"}; 
//        cbxtenlop.setModel(new DefaultComboBoxModel(s));
        List<LopDTO> listlop = new ArrayList<LopDTO>();
        LopDAO lop = new LopDAO();
        listlop = lop.getAll();
        for (LopDTO l : listlop) {
            cbxtenlop.addItem(l.getTenlop());
        }
    }

    private void uploaddata(List<HocSinhDTO> list) {
        LopDAO lop = new LopDAO();

        Object[][] data = new Object[list.size()][7];
        int i = 0;
        for (HocSinhDTO hs : list) {
            data[i][0] = hs.getTenhs();
            data[i][1] = hs.getMahs();
            data[i][2] = hs.getGioitinh();
            data[i][3] = hs.getNgaysinh();
            data[i][4] = hs.getQuequan();
            data[i][5] = hs.getSodienthoai();

            data[i][6] = hs.getTenlop();
            i++;
        }
        TableModel tableModel = new DefaultTableModel(data, colName);
        tablethongtinhocsinh.setModel(tableModel);
    }
    // Show thông tin học sinh khi load form Quản Lý Học Sinh

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtmahs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        btnNhap = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablethongtinhocsinh = new javax.swing.JTable();
        cbxNgaysinh = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        cbxthangsinh = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        cbxnamsinh = new javax.swing.JComboBox<String>();
        abc = new javax.swing.JLabel();
        cbxtenlop = new javax.swing.JComboBox<String>();
        txttenhocsinh = new javax.swing.JTextField();
        txtsodienthoai = new javax.swing.JTextField();
        txtquequan = new javax.swing.JTextField();
        rbtnma = new javax.swing.JRadioButton();
        rbtnlop = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuthongtinhocsinh = new javax.swing.JMenu();
        menuquanlydiem = new javax.swing.JMenu();
        menuquanlytaikhoan = new javax.swing.JMenu();
        menudangxuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Học Sinh");

        jLabel1.setText("Mã Học Sinh");

        jLabel2.setText("Tên Hoc Sinh");

        jLabel3.setText("Quê Quán");

        jLabel4.setText("Số Điện Thoại");

        jLabel5.setText("Ngày Sinh");

        jLabel6.setText("Giới Tính");

        buttonGroup1.add(rbtnNam);
        rbtnNam.setSelected(true);
        rbtnNam.setText("Nam");

        buttonGroup1.add(rbtnNu);
        rbtnNu.setText("Nữ");
        rbtnNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNuActionPerformed(evt);
            }
        });

        btnNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/input.png"))); // NOI18N
        btnNhap.setText("Nhập");
        btnNhap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rubbish-bin.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        btnTim.setText("Tìm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        tablethongtinhocsinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablethongtinhocsinh.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tablethongtinhocsinh);

        cbxNgaysinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxNgaysinh.setEnabled(false);

        jLabel7.setText("Tháng");

        cbxthangsinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxthangsinh.setEnabled(false);

        jLabel8.setText("Năm");

        cbxnamsinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002" }));
        cbxnamsinh.setEnabled(false);

        abc.setText("Lớp");

        cbxtenlop.setEnabled(false);
        cbxtenlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtenlopActionPerformed(evt);
            }
        });

        txttenhocsinh.setEnabled(false);

        txtsodienthoai.setEnabled(false);

        txtquequan.setEnabled(false);

        buttonGroup2.add(rbtnma);
        rbtnma.setSelected(true);
        rbtnma.setText("Mã HS");
        rbtnma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnlop);
        rbtnlop.setText("Mã Lớp");
        rbtnlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnlopActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuthongtinhocsinh.setText("Thông Tin Học Sinh");
        jMenuBar1.add(menuthongtinhocsinh);

        menuquanlydiem.setText("Quản Lý Điểm");
        jMenuBar1.add(menuquanlydiem);

        menuquanlytaikhoan.setText("Quản Lý Tài Khoản");
        menuquanlytaikhoan.setEnabled(false);
        jMenuBar1.add(menuquanlytaikhoan);

        menudangxuat.setText("Đăng Xuất");
        menudangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menudangxuatMouseClicked(evt);
            }
        });
        jMenuBar1.add(menudangxuat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addComponent(cbxtenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttenhocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbxNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(55, 55, 55)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(rbtnNam)
                                        .addGap(31, 31, 31)
                                        .addComponent(rbtnNu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxthangsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(btnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnma)
                .addGap(44, 44, 44)
                .addComponent(rbtnlop)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txttenhocsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnNam)
                            .addComponent(rbtnNu)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbxNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbxthangsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cbxnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnXoa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTim)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnma)
                    .addComponent(rbtnlop))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxtenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxtenlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtenlopActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxtenlopActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        txtmahs.setEnabled(true);
        txttenhocsinh.setEnabled(false);
        txtquequan.setEnabled(false);
        txtsodienthoai.setEnabled(false);
        cbxNgaysinh.setEnabled(false);
        cbxtenlop.setEnabled(false);
        cbxthangsinh.setEnabled(false);
        cbxnamsinh.setEnabled(false);
        rbtnNu.setEnabled(false);
        rbtnNam.setEnabled(false);

        HocSinhDTO HS = new HocSinhDTO();
        List<HocSinhDTO> dshs = new ArrayList<HocSinhDTO>();

        if (rbtnma.isSelected()) {
            HS = hocsinh.getByMa(txtmahs.getText());
            this.uploaddata(hocsinh.TimKiem(txtmahs.getText()));
        } else if (rbtnlop.isSelected()) {
            List<LopDTO> dsLop = new ArrayList<LopDTO>();
            LopDAO lop = new LopDAO();
            dsLop = lop.getAll();
            for (LopDTO l : dsLop) {
                if (cbxtenlop.getSelectedItem().toString().equals(l.getTenlop())) {
                    HS.setMalop(l.getMalop());
                }

            }
            dshs = hocsinh.getByMaLop(HS.getMalop());
            this.uploaddata(dshs);
        }

    }//GEN-LAST:event_btnTimActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        txtmahs.setEnabled(true);
        txttenhocsinh.setEnabled(false);
        txtquequan.setEnabled(false);
        txtsodienthoai.setEnabled(false);
        cbxNgaysinh.setEnabled(false);
        cbxtenlop.setEnabled(false);
        cbxthangsinh.setEnabled(false);
        cbxnamsinh.setEnabled(false);
        rbtnNu.setEnabled(false);
        rbtnNam.setEnabled(false);
        
        QuanLyHocSinhBLO qlhs = new QuanLyHocSinhBLO();
        HocSinhDTO hocsinh = new HocSinhDTO();
        HocSinhDAO hs = new HocSinhDAO();
        String mahs = txtmahs.getText();
        hocsinh.setMahs(mahs);
        String gioitinh = "Nam";
        if (rbtnNu.isSelected()) {
            gioitinh = "Nữ";
        }
        hocsinh.setGioitinh(gioitinh);

        List<LopDTO> list = new ArrayList<LopDTO>();
        LopDAO lop = new LopDAO();
        list = lop.getAll();
        for (LopDTO l : list) {
            if (cbxtenlop.getSelectedItem().toString().equals(l.getTenlop())) {
                hocsinh.setMalop(l.getMalop());
            }

        };

        String ngaysinh = cbxNgaysinh.getSelectedItem().toString() + "-" + cbxthangsinh.getSelectedItem().toString() + "-" + cbxnamsinh.getSelectedItem().toString();
        hocsinh.setNgaysinh(ngaysinh);
        String quequan = txtquequan.getText();
        hocsinh.setQuequan(quequan);
        int sodienthoai = Integer.parseInt(txtsodienthoai.getText());
        hocsinh.setSodienthoai(sodienthoai);
        String tenhs = txttenhocsinh.getText();
        hocsinh.setTenhs(tenhs);

        System.out.println(hocsinh);
        boolean x = hs.update(hocsinh);
        if (!x) {
            List<HocSinhDTO> list1 = new HocSinhDAO().getAll();
            uploaddata(list1);
            JOptionPane.showMessageDialog(null, "Sửa Học Sinh Thành Công");
        } else {
            JOptionPane.showMessageDialog(null, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtmahs.setEnabled(true);
        txttenhocsinh.setEnabled(false);
        txtquequan.setEnabled(false);
        txtsodienthoai.setEnabled(false);
        cbxNgaysinh.setEnabled(false);
        cbxtenlop.setEnabled(false);
        cbxthangsinh.setEnabled(false);
        cbxnamsinh.setEnabled(false);
        rbtnNu.setEnabled(false);
        rbtnNam.setEnabled(false);

        QuanLyHocSinhBLO qlhs = new QuanLyHocSinhBLO();
        HocSinhDTO hocsinh = new HocSinhDTO();
        HocSinhDAO hs = new HocSinhDAO();
        String mahs = txtmahs.getText();
        hocsinh.setMahs(mahs);
        String gioitinh = "Nam";
        if (rbtnNu.isSelected()) {
            gioitinh = "Nữ";
        }
        hocsinh.setGioitinh(gioitinh);

        List<LopDTO> list = new ArrayList<LopDTO>();
        LopDAO lop = new LopDAO();
        list = lop.getAll();
        for (LopDTO l : list) {
            if (cbxtenlop.getSelectedItem().toString().equals(l.getTenlop())) {
                hocsinh.setMalop(l.getMalop());
            }

        };

        String ngaysinh = cbxNgaysinh.getSelectedItem().toString() + "-" + cbxthangsinh.getSelectedItem().toString() + "-" + cbxnamsinh.getSelectedItem().toString();
        hocsinh.setNgaysinh(ngaysinh);
        String quequan = txtquequan.getText();
        hocsinh.setQuequan(quequan);
        int sodienthoai = Integer.parseInt(txtsodienthoai.getText());
        hocsinh.setSodienthoai(sodienthoai);
        String tenhs = txttenhocsinh.getText();
        hocsinh.setTenhs(tenhs);

        System.out.println(hocsinh);
        int x = hs.insert(hocsinh);
        if (x > 0) {
            List<HocSinhDTO> list1 = new HocSinhDAO().getAll();
            uploaddata(list1);
            JOptionPane.showMessageDialog(null, "Thêm Học Sinh Thành Công");
        } else {
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here:

        txttenhocsinh.setEnabled(true);
        txtquequan.setEnabled(true);
        txtsodienthoai.setEnabled(true);
        cbxNgaysinh.setEnabled(true);
        cbxtenlop.setEnabled(true);
        cbxthangsinh.setEnabled(true);
        cbxnamsinh.setEnabled(true);
        rbtnNu.setEnabled(true);
        rbtnNam.setEnabled(true);
    }//GEN-LAST:event_btnNhapActionPerformed

    private void rbtnNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtnNuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        txtmahs.setEnabled(true);
        txttenhocsinh.setEnabled(false);
        txtquequan.setEnabled(false);
        txtsodienthoai.setEnabled(false);
        cbxNgaysinh.setEnabled(false);
        cbxtenlop.setEnabled(false);
        cbxthangsinh.setEnabled(false);
        cbxnamsinh.setEnabled(false);
        rbtnNu.setEnabled(false);
        rbtnNam.setEnabled(false);
         String mahs = txtmahs.getText();
        boolean check =  hocsinh.delete(mahs);
        if(!check){
            List<HocSinhDTO> list1 = new HocSinhDAO().getAll();
            uploaddata(list1);
            JOptionPane.showMessageDialog(this, "Xóa thành công.");
            
        }else{
            List<HocSinhDTO> list1 = new HocSinhDAO().getAll();
            uploaddata(list1);
            JOptionPane.showMessageDialog(this, "Xóa không thành công.");
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void rbtnmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmaActionPerformed
        // TODO add your handling code here:
        txtmahs.setEnabled(true);
        txttenhocsinh.setEnabled(false);
        txtquequan.setEnabled(false);
        txtsodienthoai.setEnabled(false);
        cbxNgaysinh.setEnabled(false);
        cbxtenlop.setEnabled(false);
        cbxthangsinh.setEnabled(false);
        cbxnamsinh.setEnabled(false);
        rbtnNu.setEnabled(false);
        rbtnNam.setEnabled(false);
    }//GEN-LAST:event_rbtnmaActionPerformed

    private void rbtnlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnlopActionPerformed
        // TODO add your handling code here:
        txtmahs.setEnabled(false);
        txttenhocsinh.setEnabled(false);
        txtquequan.setEnabled(false);
        txtsodienthoai.setEnabled(false);
        cbxNgaysinh.setEnabled(false);
        cbxtenlop.setEnabled(true);
        cbxthangsinh.setEnabled(false);
        cbxnamsinh.setEnabled(false);
        rbtnNu.setEnabled(false);
        rbtnNam.setEnabled(false);
    }//GEN-LAST:event_rbtnlopActionPerformed

    private void menudangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menudangxuatMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        DangnhapGUI login = new DangnhapGUI();
        login.setVisible(true);
    }//GEN-LAST:event_menudangxuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyhocsinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanlyhocsinhGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abc;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxNgaysinh;
    private javax.swing.JComboBox<String> cbxnamsinh;
    private javax.swing.JComboBox<String> cbxtenlop;
    private javax.swing.JComboBox<String> cbxthangsinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menudangxuat;
    private javax.swing.JMenu menuquanlydiem;
    private javax.swing.JMenu menuquanlytaikhoan;
    private javax.swing.JMenu menuthongtinhocsinh;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JRadioButton rbtnlop;
    private javax.swing.JRadioButton rbtnma;
    private javax.swing.JTable tablethongtinhocsinh;
    private javax.swing.JTextField txtmahs;
    private javax.swing.JTextField txtquequan;
    private javax.swing.JTextField txtsodienthoai;
    private javax.swing.JTextField txttenhocsinh;
    // End of variables declaration//GEN-END:variables
}
